# Generated by Django 3.0.5 on 2021-04-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0002_auto_20210409_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('get_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men_Fashion', 'Men_Fashion'), ('Woman_Fashion', 'Woman_Fashion'), ('Electronics', 'Electronics'), ('Footwear', 'Footwear'), ('Beauty', 'Beauty'), ('Home', 'Home'), ('Gadgets', 'Gadgets'), ('Jewellery', 'Jewellery'), ('Other', 'Other')], default='', max_length=15),
        ),
    ]
