# Generated by Django 3.0.5 on 2021-04-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0003_auto_20210415_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='get_id',
            new_name='msg_id',
        ),
    ]
