# Generated by Django 3.0.5 on 2021-04-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0004_auto_20210415_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=3000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=25)),
                ('state', models.CharField(default='', max_length=30)),
                ('zip_code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
