# Generated by Django 3.0.5 on 2021-04-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0005_auto_20210418_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateorder',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=3000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
