# Generated by Django 3.0.5 on 2021-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0006_updateorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
